name: "Update Docker Image"

# Adaptation of https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: "Image Tag"
        required: true
        type: string

env:
  IMAGE_ID: ghcr.io/khronosgroupactions/android-ndk-build:${{ inputs.image-tag }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: LS
        run: ls

      - name: Build Image
        run: docker build --tag $IMAGE_ID .

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Image
        run: docker push $IMAGE_ID
